namespace CretNet.Platform.Blazor.Ui.Components;

/// <summary>Inline SVG icon set for the Cn components (S-073, shell icons S-083).</summary>
public enum CnIconKind
{
    Add,
    Archive,
    ArrowDownload,
    ArrowLeft,
    ArrowRight,
    ArrowSync,
    ArrowUndo,
    Bell,
    BookOpen,
    Box,
    Briefcase,
    Calculator,
    CheckCircle,
    Checkmark,
    Coins,
    Copy,
    Delete,
    Dismiss,
    Document,
    DocumentAdd,
    DocumentStack,
    Edit,
    ErrorCircle,
    Folder,
    Home,
    InfoCircle,
    Menu,
    PanelLeft,
    People,
    Play,
    Save,
    Search,
    Send,
    Settings,
    Shop,
    Stop,
    Subtract,
    SwapArrows,
    Warning,
    TaskCheck,
}
