name: Build

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Fetch unshallow
      run: git fetch --unshallow

    - name: Install .NET
      uses: actions/setup-dotnet@v1
      with:
        global-json-file: ./global.json

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v1.1.1
      with:
        versionSpec: "5.x"

    - name: Run GitVersion
      uses: gittools/actions/gitversion/execute@v1.1.1
      with:
        versionSpec: "5.x"

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release