name: NuGet Package CI/CD

on:
  push:
    branches: ["main", "develop"]

jobs:
  cicd:
    name: CI/CD
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Fetch unshallow
      run: git fetch --unshallow

    - name: Install .NET
      uses: actions/setup-dotnet@v4
      with:
        global-json-file: ./global.json

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v1.1.1
      with:
        versionSpec: "5.x"

    - name: Run GitVersion
      uses: gittools/actions/gitversion/execute@v1.1.1
      with:
        versionSpec: "5.x"

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release

    - name: Test
      run: dotnet test --configuration Release

    - name: Create DotNetJet NuGet package
      run: dotnet pack --configuration Release /p:PackageVersion=${{ env.GitVersion_FullSemVer }}
      working-directory: DotNetJet

    - name: Push DotNetJet NuGet package
      run: nuget push **/*.nupkg -Source https://api.nuget.org/v3/index.json -ApiKey ${{ secrets.NUGET_GALLERY_APIKEY }}
      working-directory: DotNetJet/bin/Release

    - name: Create DotNetJet.Blazor NuGet package
      run: dotnet pack --configuration Release /p:PackageVersion=${{ env.GitVersion_FullSemVer }}
      working-directory: DotNetJet.Blazor

    - name: Push DotNetJet.Blazor NuGet package
      run: nuget push **/*.nupkg -Source https://api.nuget.org/v3/index.json -ApiKey ${{ secrets.NUGET_GALLERY_APIKEY }}
      working-directory: DotNetJet.Blazor/bin/Release

    - name: Create DotNetJet.FluentValidation.DependencyInjection NuGet package
      run: dotnet pack --configuration Release /p:PackageVersion=${{ env.GitVersion_FullSemVer }}
      working-directory: DotNetJet.FluentValidation.DependencyInjection

    - name: Push DotNetJet.FluentValidation.DependencyInjection NuGet package
      run: nuget push **/*.nupkg -Source https://api.nuget.org/v3/index.json -ApiKey ${{ secrets.NUGET_GALLERY_APIKEY }}
      working-directory: DotNetJet.FluentValidation.DependencyInjection/bin/Release
