name: NuGet Package CI/CD

on:
  push:
    branches: ["main", "develop"]

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yaml

  test:
    name: Test
    needs: build
    uses: ./.github/workflows/test.yaml
  
  deploy:
    name: Deploy to NuGet Gallery
    needs: test
    uses: ./.github/workflows/deploy.yaml
    secrets: inherit
