name: NuGet Package CI/CD

on:
  push:
    branches: ["main", "develop"]
  workflow_dispatch:

jobs:
  cicd:
    name: CI/CD
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Fetch unshallow
      run: git fetch --unshallow

    - name: Install .NET
      uses: actions/setup-dotnet@v4
      with:
        global-json-file: ./global.json

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v3.2.1
      with:
        versionSpec: "6.x"

    - name: Run GitVersion
      uses: gittools/actions/gitversion/execute@v3.2.1
      with:
        versionSpec: "6.x"

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release

    - name: Test
      run: dotnet test --configuration Release

    - name: Create NuGet packages
      run: |
        for proj in $(find . -name "DotNetJet*.csproj" ! -name "*.Tests.csproj"); do
          dotnet pack "$proj" --configuration Release /p:PackageVersion=${GITVERSION_FULLSEMVER} --output packages
        done

    - name: Push NuGet packages
      run: |
        dotnet nuget push "packages/*.nupkg" --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_GALLERY_APIKEY }}
