name: Test

on:
  workflow_call:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet: ['6.0', '7.0', '8.0']
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet }}.x

    - name: Test
      run: dotnet test --configuration Release --framework net${{ matrix.dotnet }}