name: Test

on:
  workflow_call:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install .NET
      uses: actions/setup-dotnet@v4
      with:
        global-json-file: ./global.json

    - name: Restore dependencies
      run: dotnet restore

    - name: Test
      run: dotnet test --configuration Release --verbosity detailed